use crate::db::queries;
use log::info;
use rusqlite::Connection;
use std::path::Path;

/// Generate summary.html and catalogue.html in the output directory.
pub fn generate_report(conn: &Connection, output_dir: &Path) -> Result<(), String> {
    generate_summary(conn, output_dir)?;
    generate_catalogue(conn, output_dir)?;
    Ok(())
}

fn generate_summary(conn: &Connection, output_dir: &Path) -> Result<(), String> {
    let stats = queries::get_summary_stats(conn)
        .map_err(|e| format!("DB error: {}", e))?;

    let year_bars: String = stats
        .files_per_year
        .iter()
        .map(|(year, count)| {
            let max_count = stats.files_per_year.iter().map(|(_, c)| *c).max().unwrap_or(1);
            let pct = (*count as f64 / max_count as f64 * 100.0) as u32;
            format!(
                r#"<div class="bar-row"><span class="year">{}</span><div class="bar" style="width:{}%"></div><span class="count">{}</span></div>"#,
                year, pct, count
            )
        })
        .collect();

    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Fix My Takeout — Summary</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         background: #fff; color: #2c2c2c; padding: 40px; }}
  @media (prefers-color-scheme: dark) {{
    body {{ background: #1a1717; color: #f5f0f0; }}
    .card, .chart {{ background: #252121; border-color: #3a3232; }}
  }}
  h1 {{ font-size: 28px; margin-bottom: 8px; }}
  .subtitle {{ color: #a39e9e; margin-bottom: 32px; }}
  .cards {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 12px; margin-bottom: 40px; }}
  .card {{ background: white; border-radius: 10px; padding: 20px; border: 1px solid #F6EAE9; }}
  .card .label {{ font-size: 13px; color: #a39e9e; margin-bottom: 4px; }}
  .card .value {{ font-size: 24px; font-weight: 600; }}
  h2 {{ font-size: 20px; margin-bottom: 16px; }}
  .chart {{ background: white; border-radius: 10px; padding: 24px; border: 1px solid #F6EAE9; }}
  .bar-row {{ display: flex; align-items: center; gap: 8px; margin-bottom: 6px; }}
  .year {{ width: 50px; text-align: right; font-size: 13px; font-weight: 500; }}
  .bar {{ height: 18px; background: #FE655F; border-radius: 9px; min-width: 2px; }}
  .count {{ font-size: 13px; color: #a39e9e; }}
  nav {{ margin-bottom: 32px; }}
  nav a {{ color: #FE655F; font-size: 14px; text-decoration: none; }}
  nav a:hover {{ text-decoration: underline; }}
  .footer {{ margin-top: 40px; font-size: 13px; color: #a39e9e; }}
</style>
</head>
<body>
<nav><a href="catalogue.html">Browse catalogue &rarr;</a></nav>
<h1>Fix My Takeout Summary</h1>
<p class="subtitle">Your photo library has been organized</p>

<div class="cards">
  <div class="card"><div class="label">Total Files</div><div class="value">{total}</div></div>
  <div class="card"><div class="label">Photos</div><div class="value">{photos}</div></div>
  <div class="card"><div class="label">Videos</div><div class="value">{videos}</div></div>
  <div class="card"><div class="label">Live Photos</div><div class="value">{live}</div></div>
  <div class="card"><div class="label">Screenshots</div><div class="value">{screenshots}</div></div>
  <div class="card"><div class="label">RAW Images</div><div class="value">{raw}</div></div>
  <div class="card"><div class="label">Favourites</div><div class="value">{favs}</div></div>
  <div class="card"><div class="label">Hidden</div><div class="value">{hidden}</div></div>
  <div class="card"><div class="label">Recently Deleted</div><div class="value">{deleted}</div></div>
  <div class="card"><div class="label">Duplicates Found</div><div class="value">{dupes}</div></div>
  <div class="card"><div class="label">Unknown Date</div><div class="value">{unknown}</div></div>
  <div class="card"><div class="label">Albums</div><div class="value">{albums}</div></div>
</div>

<h2>Files per Year</h2>
<div class="chart">
{year_bars}
</div>

<p class="footer">Generated by Fix My Takeout</p>
</body>
</html>"#,
        total = stats.total_files,
        photos = stats.photos,
        videos = stats.videos,
        live = stats.live_photos,
        screenshots = stats.screenshots,
        raw = stats.raw_images,
        favs = stats.favourites,
        hidden = stats.hidden,
        deleted = stats.recently_deleted,
        dupes = stats.duplicates,
        unknown = stats.unknown_date,
        albums = stats.albums_count,
        year_bars = year_bars,
    );

    let report_path = output_dir.join("summary.html");
    std::fs::write(&report_path, html)
        .map_err(|e| format!("Failed to write report: {}", e))?;

    info!("Report written to {}", report_path.display());
    Ok(())
}

fn generate_catalogue(conn: &Connection, output_dir: &Path) -> Result<(), String> {
    let entries = queries::get_catalogue_entries(conn)
        .map_err(|e| format!("DB error: {}", e))?;

    // Build a JSON array of catalogue entries with absolute paths for file:// thumbnails
    let json_entries: Vec<String> = entries
        .iter()
        .map(|e| {
            format!(
                r#"[{},{},{},{},{}]"#,
                json_escape(&e.filename),
                json_escape(&e.path),
                json_escape(&e.media_type),
                e.file_size,
                json_escape(e.date_taken.as_deref().unwrap_or("")),
            )
        })
        .collect();

    let json_data = format!("[{}]", json_entries.join(","));

    let html = format!(
        r##"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Fix My Takeout — Catalogue</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  :root {{
    --bg: #fff; --surface: #fff; --border: #F6EAE9; --text: #2c2c2c;
    --secondary: #a39e9e; --accent: #FE655F; --row-hover: rgba(254,101,95,0.04);
    --thumb-bg: #f8f4f4;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{
      --bg: #1a1717; --surface: #252121; --border: #3a3232; --text: #f5f0f0;
      --secondary: #8a8080; --accent: #FE655F; --row-hover: rgba(254,101,95,0.08);
      --thumb-bg: #2a2424;
    }}
  }}
  html, body {{ height: 100%; overflow: hidden; }}
  body {{
    font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    font-size: 13px; line-height: 1.5; color: var(--text); background: var(--bg);
    -webkit-font-smoothing: antialiased;
    display: flex; flex-direction: column;
  }}
  nav {{
    flex-shrink: 0; z-index: 10; background: var(--bg);
    border-bottom: 1px solid var(--border); padding: 12px 24px;
    display: flex; align-items: center; gap: 12px;
  }}
  nav a {{ color: var(--accent); font-size: 13px; text-decoration: none; flex-shrink: 0; }}
  nav a:hover {{ text-decoration: underline; }}
  .search {{
    flex: 1; max-width: 320px; padding: 6px 12px; border-radius: 6px;
    border: 1px solid var(--border); background: var(--surface); font: inherit;
    color: var(--text); outline: none;
  }}
  .search:focus {{ border-color: var(--accent); }}
  .count {{ font-size: 12px; color: var(--secondary); font-variant-numeric: tabular-nums; flex-shrink: 0; }}
  .view-toggle {{
    display: flex; gap: 2px; margin-left: auto; flex-shrink: 0;
  }}
  .view-btn {{
    width: 30px; height: 30px; border-radius: 6px; border: 1px solid var(--border);
    background: var(--surface); cursor: pointer; display: flex; align-items: center;
    justify-content: center; color: var(--secondary); transition: all 0.15s;
  }}
  .view-btn:hover {{ border-color: var(--accent); color: var(--text); }}
  .view-btn.active {{ background: var(--accent); color: #fff; border-color: var(--accent); }}
  .toolbar {{
    flex-shrink: 0; padding: 8px 24px; display: flex; gap: 6px; flex-wrap: wrap;
    border-bottom: 1px solid var(--border);
  }}
  .chip {{
    padding: 4px 12px; border-radius: 14px; border: 1px solid var(--border);
    background: var(--surface); font: 12px inherit; cursor: pointer; color: var(--text);
    transition: all 0.15s;
  }}
  .chip:hover {{ border-color: var(--accent); }}
  .chip.active {{ background: var(--accent); color: #fff; border-color: var(--accent); }}

  /* List view */
  .viewport {{ flex: 1; overflow-y: auto; position: relative; }}
  .spacer {{ position: relative; }}
  .row {{
    display: grid; grid-template-columns: 36px 2fr 1fr 80px 100px; gap: 10px;
    padding: 4px 24px; align-items: center; font-size: 13px;
    position: absolute; left: 0; right: 0;
  }}
  .row {{ cursor: pointer; }}
  .row:hover {{ background: var(--row-hover); }}
  .row-thumb, .row-thumb-video {{
    width: 36px; height: 36px; border-radius: 4px; object-fit: cover;
    background: var(--thumb-bg); flex-shrink: 0;
  }}
  .row-thumb-placeholder {{
    width: 36px; height: 36px; border-radius: 4px; background: var(--thumb-bg);
    display: flex; align-items: center; justify-content: center;
    font-size: 10px; color: var(--secondary); text-transform: uppercase;
    flex-shrink: 0;
  }}
  .fname {{
    overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
    font-weight: 500;
  }}
  .ftype {{
    font-size: 11px; color: var(--secondary); text-transform: uppercase;
    letter-spacing: 0.3px;
  }}
  .fdate {{ font-size: 12px; color: var(--secondary); }}
  .fsize {{
    text-align: right; font-size: 12px; color: var(--secondary);
    font-variant-numeric: tabular-nums;
  }}

  /* List header for sorting */
  .list-header {{
    display: grid; grid-template-columns: 36px 2fr 1fr 80px 100px; gap: 10px;
    padding: 6px 24px; font-size: 11px; font-weight: 600; color: var(--secondary);
    text-transform: uppercase; letter-spacing: 0.3px; border-bottom: 1px solid var(--border);
    flex-shrink: 0; user-select: none;
  }}
  .list-header span {{ cursor: pointer; display: flex; align-items: center; gap: 3px; }}
  .list-header span:hover {{ color: var(--text); }}
  .sort-arrow {{ font-size: 9px; }}

  /* Grid view */
  .grid-container {{ flex: 1; overflow-y: auto; position: relative; }}
  .grid-spacer {{ position: relative; }}
  .grid-item {{
    position: absolute; display: flex; flex-direction: column;
    overflow: hidden; cursor: default;
  }}
  .grid-thumb, .grid-thumb-video {{
    width: 100%; aspect-ratio: 1; object-fit: cover; border-radius: 6px;
    background: var(--thumb-bg); display: block;
  }}
  .grid-item {{ cursor: pointer; }}
  .vid-badge {{
    position: absolute; top: 6px; right: 6px; background: rgba(0,0,0,0.55);
    color: #fff; font-size: 9px; font-weight: 600; padding: 1px 5px;
    border-radius: 3px; letter-spacing: 0.3px;
  }}
  .play-btn {{
    position: absolute; bottom: 6px; left: 6px; width: 28px; height: 28px;
    border-radius: 50%; background: rgba(0,0,0,0.55); border: none;
    color: #fff; cursor: pointer; display: flex; align-items: center;
    justify-content: center; transition: background 0.15s; z-index: 2;
    backdrop-filter: blur(4px); -webkit-backdrop-filter: blur(4px);
  }}
  .play-btn:hover {{ background: rgba(0,0,0,0.75); }}
  .play-btn svg {{ width: 12px; height: 12px; fill: #fff; }}
  .grid-thumb-placeholder {{
    width: 100%; aspect-ratio: 1; border-radius: 6px; background: var(--thumb-bg);
    display: flex; align-items: center; justify-content: center;
    font-size: 12px; color: var(--secondary); text-transform: uppercase;
  }}
  .grid-label {{
    font-size: 11px; font-weight: 500; padding: 4px 2px 0;
    overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  }}
  .grid-meta {{
    font-size: 10px; color: var(--secondary); padding: 0 2px;
  }}
</style>
</head>
<body>

<nav>
  <a href="summary.html">&larr; Summary</a>
  <input class="search" type="text" placeholder="Search files..." id="search">
  <span class="count" id="count"></span>
  <div class="view-toggle">
    <button class="view-btn active" id="btn-grid" title="Grid view">
      <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><rect x="1" y="1" width="5" height="5" rx="1" fill="currentColor"/><rect x="8" y="1" width="5" height="5" rx="1" fill="currentColor"/><rect x="1" y="8" width="5" height="5" rx="1" fill="currentColor"/><rect x="8" y="8" width="5" height="5" rx="1" fill="currentColor"/></svg>
    </button>
    <button class="view-btn" id="btn-list" title="List view">
      <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><rect x="1" y="2" width="12" height="2" rx="1" fill="currentColor"/><rect x="1" y="6" width="12" height="2" rx="1" fill="currentColor"/><rect x="1" y="10" width="12" height="2" rx="1" fill="currentColor"/></svg>
    </button>
  </div>
</nav>
<div class="toolbar" id="filters"></div>

<div class="list-header" id="list-header">
  <span></span>
  <span data-col="name">Name <span class="sort-arrow" id="sort-name"></span></span>
  <span data-col="type">Type <span class="sort-arrow" id="sort-type"></span></span>
  <span data-col="date">Date <span class="sort-arrow" id="sort-date"></span></span>
  <span data-col="size">Size <span class="sort-arrow" id="sort-size"></span></span>
</div>
<div class="viewport" id="viewport">
  <div class="spacer" id="spacer"></div>
</div>
<div class="grid-container" id="grid-container" style="display:none">
  <div class="grid-spacer" id="grid-spacer"></div>
</div>

<script>
const DATA = {data};
// Each entry: [filename, absolutePath, mediaType, fileSize, dateTaken]
const ROW_H = 44;
const OVERSCAN = 8;
const IMAGE_TYPES = new Set(['image', 'raw_image', 'live_photo_image', 'screenshot']);
const VIDEO_TYPES = new Set(['video', 'live_photo_video']);

const types = [...new Set(DATA.map(d => d[2]))].sort();
const filterEl = document.getElementById('filters');
let activeType = null;

// "All" chip first
const allChip = document.createElement('button');
allChip.className = 'chip active';
allChip.textContent = 'All';
allChip.onclick = () => {{
  activeType = null;
  filterEl.querySelectorAll('.chip').forEach(c => c.classList.remove('active'));
  allChip.classList.add('active');
  applyFilter();
}};
filterEl.appendChild(allChip);

types.forEach(t => {{
  const chip = document.createElement('button');
  chip.className = 'chip';
  chip.textContent = t.replace(/_/g, ' ');
  chip.onclick = () => {{
    filterEl.querySelectorAll('.chip').forEach(c => c.classList.remove('active'));
    activeType = t;
    chip.classList.add('active');
    applyFilter();
  }};
  filterEl.appendChild(chip);
}});

const searchEl = document.getElementById('search');
const countEl = document.getElementById('count');
const viewport = document.getElementById('viewport');
const spacer = document.getElementById('spacer');
const gridContainer = document.getElementById('grid-container');
const gridSpacer = document.getElementById('grid-spacer');
const listHeader = document.getElementById('list-header');
const btnGrid = document.getElementById('btn-grid');
const btnList = document.getElementById('btn-list');

let filtered = DATA;
let renderedRows = new Map();
let renderedGrid = new Map();
let viewMode = 'grid';

// Sorting state
let sortCol = 'date';
let sortAsc = false; // newest first by default
const sortArrows = {{ name: document.getElementById('sort-name'), type: document.getElementById('sort-type'), date: document.getElementById('sort-date'), size: document.getElementById('sort-size') }};

function updateSortArrows() {{
  Object.entries(sortArrows).forEach(([col, el]) => {{
    el.textContent = col === sortCol ? (sortAsc ? '\u25B2' : '\u25BC') : '';
  }});
}}

function sortFiltered() {{
  const col = sortCol;
  const dir = sortAsc ? 1 : -1;
  filtered.sort((a, b) => {{
    let va, vb;
    if (col === 'name') {{ va = a[0].toLowerCase(); vb = b[0].toLowerCase(); return va < vb ? -dir : va > vb ? dir : 0; }}
    if (col === 'type') {{ va = a[2]; vb = b[2]; return va < vb ? -dir : va > vb ? dir : 0; }}
    if (col === 'date') {{ va = a[4] || ''; vb = b[4] || ''; return va < vb ? -dir : va > vb ? dir : 0; }}
    if (col === 'size') {{ return (a[3] - b[3]) * dir; }}
    return 0;
  }});
}}

listHeader.querySelectorAll('[data-col]').forEach(el => {{
  el.onclick = () => {{
    const col = el.dataset.col;
    if (sortCol === col) {{ sortAsc = !sortAsc; }}
    else {{ sortCol = col; sortAsc = col === 'name' || col === 'type'; }}
    updateSortArrows();
    applyFilter();
  }};
}});
updateSortArrows();

// Grid sizing
const GRID_GAP = 8;
const GRID_PAD = 24;
const GRID_LABEL_H = 36;

function getGridCols() {{
  const w = gridContainer.clientWidth - GRID_PAD * 2 + GRID_GAP;
  const minSize = 160;
  return Math.max(2, Math.floor(w / (minSize + GRID_GAP)));
}}

function getGridCellSize() {{
  const cols = getGridCols();
  return (gridContainer.clientWidth - GRID_PAD * 2 - (cols - 1) * GRID_GAP) / cols;
}}

function fileUrl(absPath) {{
  return 'file://' + encodeURI(absPath).replace(/#/g, '%23');
}}

function isImageFile(mediaType) {{
  return IMAGE_TYPES.has(mediaType);
}}

function isVideoFile(mediaType) {{
  return VIDEO_TYPES.has(mediaType);
}}

function getExt(filename) {{
  const dot = filename.lastIndexOf('.');
  return dot > 0 ? filename.substring(dot + 1).toUpperCase() : '';
}}

function revealInFinder(absPath) {{
  // Open the parent folder and select the file using macOS `open -R`
  // This works when the HTML is opened locally
  window.location.href = 'file://' + encodeURI(absPath.substring(0, absPath.lastIndexOf('/')));
}}

function makeVideoThumb(absPath, className) {{
  const video = document.createElement('video');
  video.className = className;
  video.src = fileUrl(absPath);
  video.muted = true;
  video.preload = 'metadata';
  video.addEventListener('loadedmetadata', () => {{ video.currentTime = Math.min(1, video.duration * 0.1); }});
  return video;
}}

function fmtDate(d) {{
  if (!d) return '';
  return d.substring(0, 10);
}}

function applyFilter() {{
  const q = searchEl.value.toLowerCase();
  filtered = DATA.filter(d => {{
    if (activeType && d[2] !== activeType) return false;
    if (q && !d[0].toLowerCase().includes(q)) return false;
    return true;
  }});
  sortFiltered();
  countEl.textContent = filtered.length.toLocaleString() + ' files';

  if (viewMode === 'list') {{
    spacer.style.height = (filtered.length * ROW_H) + 'px';
    renderedRows.forEach(el => el.remove());
    renderedRows.clear();
    renderList();
  }} else {{
    renderedGrid.forEach(el => el.remove());
    renderedGrid.clear();
    updateGridHeight();
    renderGrid();
  }}
}}

function updateGridHeight() {{
  const cols = getGridCols();
  const cellSize = getGridCellSize();
  const rows = Math.ceil(filtered.length / cols);
  gridSpacer.style.height = (rows * (cellSize + GRID_LABEL_H + GRID_GAP) + GRID_PAD) + 'px';
}}

function fmtSize(b) {{
  if (b > 1073741824) return (b / 1073741824).toFixed(1) + ' GB';
  if (b > 1048576) return (b / 1048576).toFixed(1) + ' MB';
  if (b > 1024) return (b / 1024).toFixed(0) + ' KB';
  return b + ' B';
}}

function renderList() {{
  const scrollTop = viewport.scrollTop;
  const viewH = viewport.clientHeight;
  const startIdx = Math.max(0, Math.floor(scrollTop / ROW_H) - OVERSCAN);
  const endIdx = Math.min(filtered.length, Math.ceil((scrollTop + viewH) / ROW_H) + OVERSCAN);

  const visible = new Set();
  for (let i = startIdx; i < endIdx; i++) visible.add(i);

  renderedRows.forEach((el, idx) => {{
    if (!visible.has(idx)) {{ el.remove(); renderedRows.delete(idx); }}
  }});

  for (let i = startIdx; i < endIdx; i++) {{
    if (renderedRows.has(i)) continue;
    const d = filtered[i];
    const row = document.createElement('div');
    row.className = 'row';
    row.style.top = (i * ROW_H) + 'px';
    row.style.height = ROW_H + 'px';
    row.onclick = () => revealInFinder(d[1]);
    row.title = 'Click to reveal in Finder';

    if (isVideoFile(d[2])) {{
      const vid = makeVideoThumb(d[1], 'row-thumb-video');
      row.appendChild(vid);
    }} else if (isImageFile(d[2])) {{
      const img = document.createElement('img');
      img.className = 'row-thumb';
      img.src = fileUrl(d[1]);
      img.loading = 'lazy';
      img.onerror = function() {{ this.outerHTML = '<div class="row-thumb-placeholder">' + getExt(d[0]) + '</div>'; }};
      row.appendChild(img);
    }} else {{
      const ph = document.createElement('div');
      ph.className = 'row-thumb-placeholder';
      ph.textContent = getExt(d[0]);
      row.appendChild(ph);
    }}

    const frag = document.createDocumentFragment();
    const fname = document.createElement('span'); fname.className = 'fname'; fname.textContent = d[0]; frag.appendChild(fname);
    const ftype = document.createElement('span'); ftype.className = 'ftype'; ftype.textContent = d[2].replace(/_/g, ' '); frag.appendChild(ftype);
    const fdate = document.createElement('span'); fdate.className = 'fdate'; fdate.textContent = fmtDate(d[4]); frag.appendChild(fdate);
    const fsize = document.createElement('span'); fsize.className = 'fsize'; fsize.textContent = fmtSize(d[3]); frag.appendChild(fsize);
    row.appendChild(frag);

    spacer.appendChild(row);
    renderedRows.set(i, row);
  }}
}}

function renderGrid() {{
  const scrollTop = gridContainer.scrollTop;
  const viewH = gridContainer.clientHeight;
  const cols = getGridCols();
  const cellSize = getGridCellSize();
  const cellH = cellSize + GRID_LABEL_H + GRID_GAP;

  const startRow = Math.max(0, Math.floor(scrollTop / cellH) - 2);
  const endRow = Math.min(Math.ceil(filtered.length / cols), Math.ceil((scrollTop + viewH) / cellH) + 2);

  const visible = new Set();
  for (let r = startRow; r < endRow; r++) {{
    for (let c = 0; c < cols; c++) {{
      const idx = r * cols + c;
      if (idx < filtered.length) visible.add(idx);
    }}
  }}

  renderedGrid.forEach((el, idx) => {{
    if (!visible.has(idx)) {{ el.remove(); renderedGrid.delete(idx); }}
  }});

  for (const idx of visible) {{
    if (renderedGrid.has(idx)) continue;
    const d = filtered[idx];
    const c = idx % cols;
    const r = Math.floor(idx / cols);

    const item = document.createElement('div');
    item.className = 'grid-item';
    item.style.left = (GRID_PAD + c * (cellSize + GRID_GAP)) + 'px';
    item.style.top = (r * cellH) + 'px';
    item.style.width = cellSize + 'px';
    item.onclick = () => revealInFinder(d[1]);
    item.title = 'Click to reveal in Finder';

    const thumbWrap = document.createElement('div');
    thumbWrap.style.position = 'relative';

    if (isVideoFile(d[2])) {{
      const vid = makeVideoThumb(d[1], 'grid-thumb-video');
      thumbWrap.appendChild(vid);
      const badge = document.createElement('span');
      badge.className = 'vid-badge';
      badge.textContent = 'VIDEO';
      thumbWrap.appendChild(badge);
      const playBtn = document.createElement('button');
      playBtn.className = 'play-btn';
      playBtn.innerHTML = '<svg viewBox="0 0 16 16"><polygon points="4,2 14,8 4,14"/></svg>';
      let playing = false;
      playBtn.onclick = (e) => {{
        e.stopPropagation();
        if (playing) {{
          vid.pause();
          vid.currentTime = Math.min(1, vid.duration * 0.1);
          playBtn.innerHTML = '<svg viewBox="0 0 16 16"><polygon points="4,2 14,8 4,14"/></svg>';
        }} else {{
          vid.play();
          playBtn.innerHTML = '<svg viewBox="0 0 16 16"><rect x="3" y="2" width="3.5" height="12" rx="1"/><rect x="9.5" y="2" width="3.5" height="12" rx="1"/></svg>';
        }}
        playing = !playing;
      }};
      vid.onended = () => {{
        playing = false;
        vid.currentTime = Math.min(1, vid.duration * 0.1);
        playBtn.innerHTML = '<svg viewBox="0 0 16 16"><polygon points="4,2 14,8 4,14"/></svg>';
      }};
      thumbWrap.appendChild(playBtn);
    }} else if (isImageFile(d[2])) {{
      const img = document.createElement('img');
      img.className = 'grid-thumb';
      img.src = fileUrl(d[1]);
      img.loading = 'lazy';
      img.onerror = function() {{ this.outerHTML = '<div class="grid-thumb-placeholder">' + getExt(d[0]) + '</div>'; }};
      thumbWrap.appendChild(img);
    }} else {{
      const ph = document.createElement('div');
      ph.className = 'grid-thumb-placeholder';
      ph.textContent = getExt(d[0]);
      thumbWrap.appendChild(ph);
    }}
    item.appendChild(thumbWrap);

    const label = document.createElement('div');
    label.className = 'grid-label';
    label.title = d[0];
    label.textContent = d[0];
    item.appendChild(label);

    const meta = document.createElement('div');
    meta.className = 'grid-meta';
    meta.textContent = fmtSize(d[3]);
    item.appendChild(meta);

    gridSpacer.appendChild(item);
    renderedGrid.set(idx, item);
  }}
}}

function setView(mode) {{
  viewMode = mode;
  if (mode === 'list') {{
    listHeader.style.display = '';
    viewport.style.display = '';
    gridContainer.style.display = 'none';
    btnList.classList.add('active');
    btnGrid.classList.remove('active');
  }} else {{
    listHeader.style.display = 'none';
    viewport.style.display = 'none';
    gridContainer.style.display = '';
    btnGrid.classList.add('active');
    btnList.classList.remove('active');
  }}
  applyFilter();
}}

function esc(s) {{ const d = document.createElement('span'); d.textContent = s; return d.innerHTML; }}

btnList.onclick = () => setView('list');
btnGrid.onclick = () => setView('grid');
searchEl.addEventListener('input', applyFilter);

// Initialize — grid is default
listHeader.style.display = 'none';
setView('grid');
viewport.addEventListener('scroll', renderList);
gridContainer.addEventListener('scroll', renderGrid);
window.addEventListener('resize', () => {{
  if (viewMode === 'grid') {{
    renderedGrid.forEach(el => el.remove());
    renderedGrid.clear();
    updateGridHeight();
    renderGrid();
  }} else {{
    renderList();
  }}
}});
</script>
</body>
</html>"##,
        data = json_data,
    );

    let catalogue_path = output_dir.join("catalogue.html");
    std::fs::write(&catalogue_path, html)
        .map_err(|e| format!("Failed to write catalogue: {}", e))?;

    info!("Catalogue written to {} ({} entries)", catalogue_path.display(), entries.len());
    Ok(())
}

fn json_escape(s: &str) -> String {
    let escaped = s
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t");
    format!("\"{}\"", escaped)
}
